# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Exchange-Diary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for frontend
  platform :ios, '16.0'

  pod 'Alamofire'
  pod 'KeychainSwift', '~> 20.0'

  #KakaoSDK
  pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
  pod 'KakaoSDKAuth'  # 사용자 인증
  pod 'KakaoSDKUser'  # 카카오 로그인, 사용자 관리

  pod 'GoogleSignIn'
  pod 'GoogleSignInSwiftSupport'

  pod 'naveridlogin-sdk-ios'

  pod 'Kingfisher'

  post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.4'
        end
      end
    end
  end

end
